### ISSUE TITLE
Laboratories Information 

### ISSUE THREAD

**Issue by AldoCervantes** [ProyectoIntegrador2018/makers#102]
Get and fill in all the laboratories information

## Conversation
Get all the information needed to fill the Innovaction Gym Laboratory, spaces and equipments and create a mock Laboratory similar to the Innovaction Gym.

## DOF

- [ ]  Be able to see and interact with 2 different Laboratories, spaces and equipments

## Relations
N/A

**Comment by AldoCervantes** [comment]
Por el momento se tiene la información guardada en un archivo excel que se utilizara como respaldo y de ayuda para que el personal de los laboratorios llene la información solicitada. 

**Para poder completar esta tarea es necesario:

- [ ] Tener la aprobación del cliente de que los datos son los correctos

- [ ] Tener acceso a heroku para volver a hacer el deploy y llenar la información

**Comment by AldoCervantes** [comment]
Debido a que el cliente no ha contestado y falta un dia para la primera revision, actualice el archivo de seeds.rb 
**Esto es temporal y en cuanto el cliente revise los datos se tiene que modificar.

**Comment by technical-boy** [comment]
Is this issue closed with #112 @AldoCervantes ?

**Comment by AldoCervantes** [comment]
No, we need the approval from the Product Owner

**Comment by AldoCervantes** [comment]
Because we haven't receive a confirmation of the Product Owner, this issue will be close in order for us to continue. In case the PO wants to make future changes this issue or another one will be open.
