### ISSUE TITLE
Lab Admin can't see their spaces and equipments

### ISSUE THREAD

**Issue by erik0686** [ProyectoIntegrador2018/makers#132]
In the admin dashboard, Lab Admins should be able to see the spaces and equipment of the labs they administrate.

## Steps for reproducing bug
1. Sign in as a Lab Admin 
2. Go to Admin dashboard
3. Click on Spaces tab

## Expected behaviour
Spaces and equipment the Lab Admin administrate should be listed 

## Current behaviour
Spaces and equipment the Lab admin administrates are not listed (nothing is listed)

**Comment by AldoCervantes** [comment]
As I mentioned on #135 this wasn't a bug, because the only problem was that the Lab Admin wasn't assigned to any Lab, but with the fix, it is now possible to assign a Lab to a Lab Admin and with this he/she is able to see their Spaces and Equipments.
