### ISSUE TITLE
Lab Space Admins do not see the equipment of the spaces they administrate

### ISSUE THREAD

**Issue by erik0686** [ProyectoIntegrador2018/makers#133]
In the admin dashboard, Lab Space Admins should be able to see the equipment of the spaces they administrate.

## Steps for reproducing bug
1. Sign in as a Lab Space Admin 
2. Go to Admin dashboard
3. Click on Equipment tab

## Expected behavior
Equipment the Lab Space Admin administrate should be listed 

## Current behavior
Equipment the Lab Space Admin administrates are not listed (nothing is listed)

**Comment by AldoCervantes** [comment]
As I mentioned on #135 this wasn't a bug, because the only problem was that the Lab Space Admin wasn't assigned to any Lab Space, but with the fix, it is now possible to assign a Lab Space to a Lab Space Admin and with this he/she is able to see their Equipments.
