### ISSUE TITLE
Lab Space Admin can't be assigned or reassigned to spaces

### ISSUE THREAD

**Issue by erik0686** [ProyectoIntegrador2018/makers#135]
When creating a lab space admin, right now it assigns the user_id of the space, referencing a user (an admin). In the lab administrations tab in the dashboard, the listed things are the Lab Administrations, not the user_id (admin) of the space. So that makes it seem as if there are no lab space admins. The possible solution is to show the relation between Admin and their spaces in the Lab Administration tab in the dashboard.

## Steps for reproducing the bug
1. Sign in as Lab Space Admin
2. Go to the dashboard
3. Click on the Lab Administration tab.

## Expected behavior
A Lab Admin must be able to assign or reassign Lab Spaces admins on the space they choose.

## Current behavior
There is no possible action to reassign admins or reassign them.

**Comment by AldoCervantes** [comment]
I change the select options to display Lab Space Admins, and in that way they could be assigned to lab spaces and labs, I am working on an explanation of how this works in order to explain the team and the PO. This migth help solving future issues regarding the 3rd Sprint.
