### ISSUE TITLE
S25 As a Lab Space Admin, I should be able to create equipments.

### ISSUE THREAD

**Issue by erik0686** [ProyectoIntegrador2018/makers#138]
## User Story Title

As a Lab Space Admin, I should be able to create equipments.

### Story points

2 story point

### Acceptance Criteria

- [ ] a Lab Space Admin can create an equipment in a space they administrate.

### Definition of Done

- [ ] All manual tests have passed (it works)
- [ ] Any new bugs caused by the addition of this feature have been addressed and solved

### Definition of Ready

- [ ] Code Climate GPA is maintained at Grade A
- [ ] Any relevant changes in documentation have been added to the Pull Request

**Comment by AldoCervantes** [comment]
This is not an issue, this is related with the assignation of lab spaces.
