### ISSUE TITLE
S27 Add the index of equipments below the search bar in the landing page

### ISSUE THREAD

**Issue by erik0686** [ProyectoIntegrador2018/makers#156]
## User Story Title

As a user I can see the index of equipments in the landing page, in order to select any equipment and go to the show view.

### Story points

5

### Conversation

In the landing page, we should be able to see the pills of the list of equipments currently in existence.

### Acceptance Criteria

- [x] the equipments are all shown in the landing page
- [x] Each equipment takes you to the equipment view.

### Definition of Done

- [x] All manual tests have passed (it works)
- [x] Any new bugs caused by the addition of this feature have been addressed and solved

### Definition of Ready

- [x] Code Climate GPA is maintained at Grade A
- [ ] Any relevant changes in documentation have been added to the Pull Request

**Comment by technical-boy** [comment]
Closed in #162
