### ISSUE TITLE
S09 Como LabAdmin puedo actualizar el estatus de una reservación

### ISSUE THREAD

**Issue by hecerinc** [ProyectoIntegrador2018/makers#17]
# S09

**Prioridad:** 09

Como LabAdmin puedo actualizar el estatus de una reservación para mantener control de la disponibilidad del equipo.

## Criterios de aceptaci&oacute;n

- [x] El usuario puede actualizar el estatus de una reservaci&oacute;n a uno de: pr&eacute;stamo, devuelto, perdido.

## To Do

- [x] Definir flujo y vistas
- [x] Implementar cambios y funciones en el controlador
- [x] Implementar vistas

## Conversaci&oacute;n

El estatus puede estar en préstamo, devuelto, perdido

**Comment by hecerinc** [comment]
@jgalvan Estos status que definimos aqu&iacute; ya no son vigentes o s&iacute;?

**Comment by jgalvan** [comment]
no, los cambiamos por [:confirmed, :complete, :cancelled, :blocked]

para referencia, están en el [modelo de reservaciones](https://github.com/ProyectoIntegrador2018/makers/blob/dev/app/models/reservation.rb)
